---
author: "Study Group 11: Nereid Kwok, Nisa Ozer, Lauren Wade, Thomas Giannetti-Fakhouri, Kazmer Nagy-Betegh, Chandrime Tolia"

title: "Final Assignment"

date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
    df_print: paged
---

```{r , echo=FALSE}


knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)


# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

```{r initialise-libraries, echo=FALSE}

library(googlesheets4)
library(tidyverse)
library(janitor) 
library(skimr)
library(countrycode) # to clean up country names
library(broom)
library(car)
library(ggfortify)
library(lubridate)
library(labourR)
library(magrittr)
library(gapminder)
library(quantmod)
library(stringr)
library(stringdist)
library(hash)
library(labourR)
```



# Data Import

```{r import-ask-manager}

# Google Sheets permissions did not work with my google account

# use googlesheets4 to get data
url <- "https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/edit?resourcekey#gid=1625408792"
googlesheets4::gs4_auth() # google sheets authorisation

# load "Ask a A Manager 2021 Survey" googlesheet
# https://www.askamanager.org/
ask_a_manager_2021 <- googlesheets4::read_sheet(url) %>%
  janitor::clean_names()

# if googlesheets is now working, read local copy
# ask_a_manager_2021 <- read_csv(here::here("data", "ask_a_manager_2021.csv"))%>%
  # janitor::clean_names()
  
```

# Intitial Data Exploration and Cleaning

```{r data-explore}

skimr::skim(ask_a_manager_2021)
```


## Clean Country Names

```{r country-code-cleaning}

# unique(ask_a_manager_2021$country) # checking the list of unique country codes reveals that country names are inconsistent across the data

ask_a_manager_2021_cleaned <- ask_a_manager_2021%>%
  mutate(
    country = countrycode::countrycode(sourcevar = ask_a_manager_2021$country, 
                                       origin = 'country.name', 
                                       destination = 'country.name', 
                                       warn = TRUE, 
                                       nomatch = NULL)
    )

ask_a_manager_2021_cleaned <- ask_a_manager_2021_cleaned%>%
  mutate(
    country = countrycode::countrycode(sourcevar = ask_a_manager_2021_cleaned$country, 
                                       origin = 'unicode.symbol', 
                                       destination = 'country.name', 
                                       warn = TRUE, 
                                       nomatch = NULL)
    )



country_list <- unique(countryname_dict$country.name.en)

typos <- ask_a_manager_2021_cleaned%>%
  filter(!country %in% unique(countryname_dict$country.name.en))
  
unique(typos$country) #identifying the the typos and mismatches that the country code library couldn't deal with

typo_map <- hash() #create a map for the correct version of the typos


typo_map[["United Kingdom"]] <- list("Scotland",
                                     "England",
                                     "Northern Ireland",
                                     "England/UK",
                                     "England, UK",
                                     "United Kindom",
                                     "UK (Northern Ireland)",                                                                                              "UK for U.S. company",
                                     "England, Gb",
                                     "Englang",
                                     "England, Gb",
                                     "U.K. (northern England)",
                                     "Unites kingdo",
                                     "Unites kingdom",
                                     "UK (England)",
                                     "england",
                                     "Jersey", 
                                     "Channel islands",
                                     "UK, remote",
                                     "Scotland, UK",
                                     "England, UK.",
                                     "Jersey, Channel islands",
                                     "Wales, UK",
                                     "Wales (UK)",
                                     "UK, but for globally fully remote company",
                                     "Wales"
                                     )
typo_map[["United States"]] <- list("United State",
  "ISA",
 "America",
"United State of America",
"United Stated",
"USA-- Virgin Islands",
"United Statws" ,
"Unites States" ,
"U. S.",
"United Sates",
"Uniited States",
"Worldwide (based in US but short term trips aroudn the world)",
"United Sates of America",
"United States (I work from home and my clients are all over the US/Canada/PR",
"Unted States",
"United Statesp",
"United Stattes",
"United Statea",
"United Statees",
"Uniyed states",
"Uniyes States",
"United Status",
"Uniteed States",
"United Stares",
"Unites states",
"Unite States",
"The US",
"United statew",
"United Statues",
"Untied States",
"Unitied States",
"United Sttes",
"united stated",
"Uniter Statez",
"U. S" ,
"United Stateds",
"Usat",
"Unitef Stated",
"USaa",
"america",
"United States- Puerto Rico",
"California",
"Virginia",
"Hartford",
"San Francisco",
"USD",
"United Statss",
"I work for a UAE-based organization, though I am personally in the US.",
"United  States",
"U.A.",
"UXZ",
"USS",
"IS",
"USAB",
"UA",
"I.S",
"I.S.",
"United y"
)

typo_map[["Canada"]] <- list(
  "Canadw",
"Can",
"Canda",
"Canada and USA",
"Csnada",
"Canad"
)

typo_map[["NA"]] <- list(
  "Contracts",
"We don't get raises, we get quarterly bonuses, but they periodically asses income in the area you work, so I got a raise because a 3rd party assessment showed I was paid too little for the area we were located",
"Global" ,
"Currently finance",
"UXZ",
"$2,175.84/year is deducted for benefits",
"Remote",
"bonus based on meeting yearly goals set w/ my supervisor",
"I earn commission on sales. If I meet quota, I'm guaranteed another 16k min. Last year i earned an additional 27k. It's not uncommon for people in my space to earn 100k+ after commission.",
"I was brought in on this salary to help with the EHR and very quickly was promoted to current position but compensation was not altered.",
"n/a (remote from wherever I want)",
"Africa",
"europe",
"na",
"Policy",
"NA",
"International",
"NZ",
"Y"
)

typo_map[["Spain"]] <- list("Catalonia")

typo_map[["Australia"]] <- list("Australi")

typo_map[["Denmark"]] <- list("Danmark")

typo_map[["Netherlands"]] <- list("NL",
"Nederland")

typo_map[["Panama"]] <- list("Panamá")

typo_map[["Brazil"]] <- list("Brasil")

typo_map[["Argentina"]] <- list("ARGENTINA BUT MY ORG IS IN THAILAND")

typo_map[["Mexico"]] <- list("México")

for (c in keys(typo_map))
{
  ask_a_manager_2021_cleaned <- ask_a_manager_2021_cleaned%>%
  mutate(country = case_when(country %in% values(typo_map, keys = c) ~c,
                              !country %in% values(typo_map, keys = c) ~ country))
}

ask_a_manager_2021_cleaned <- ask_a_manager_2021_cleaned%>%
  mutate(country_code = countrycode::countrycode(sourcevar =  ask_a_manager_2021_cleaned$country,
                                                 origin = 'country.name',
                                                 destination = 'iso3c',
                                                 nomatch = NA,
                                                 warn = TRUE))

```


```{r}
typos <- ask_a_manager_2021_cleaned%>%
  filter(!country %in% unique(countryname_dict$country.name.en))
unique(typos$country)

unique(ask_a_manager_2021_cleaned$country)
```

## Currency 

```{r }

ask_a_manager_2021_cleaned$currency <- substr(ask_a_manager_2021_cleaned$currency, 0, 3)

from <- ask_a_manager_2021_cleaned$currency
to <- c("USD")
exchange_rate <- getQuote(paste0(from, to, "=X"))
  
exchange_rate <- exchange_rate[-c(8),] 

exchange_rate <- exchange_rate %>% 
  mutate(currency = c("USD", "GBP", "CAD", "EUR", "AUD", "CHF", "ZAR", "SEK", "HKD", "JPY")) %>% 
  select(currency, Last)%>%
  clean_names()

ask_a_manager_2021_cleaned <-
  merge(ask_a_manager_2021_cleaned, exchange_rate, by="currency", all.x = T)

ask_a_manager_2021_cleaned <- ask_a_manager_2021_cleaned %>%  
  mutate(salary_usd = annual_salary * last)%>%
  clean_names()

```

## Industry

```{r industry-cleaning}
standard_industry <- c("Accounting, Banking & Finance",
                       "Agriculture or Forestry",
                       "Art & Design",
                       "Business or Consulting",
                       "Computing or Tech",
                       "Education (Primary/Secondary)",
                       "Education (Higher Education)",
                       "Engineering or Manufacturing",
                       "Entertainment",
                       "Government and Public Administration",
                       "Health care",
                       "Hospitality & Events",
                       "Insurance",
                       "Law",
                       "Law Enforrcement & Security",
                       "Leisure, Sport & Tourism",
                       "Marketing, Advertising & PR",
                       "Media & Digital",
                       "Nonprofits",
                       "Property or Construction",
                       "Recruitment or HR",
                       "Retail",
                       "Sales",
                       "Social Work",
                       "Transport or Logistics",
                       "Utilities & Telecommunications")

non_standard_industry <- c("Mining and Mentals",
                           "Aerospace & Defence",
                           "Automotive",
                           "Biotechnology",
                           "Church",
                           "Food & Bevarage",
                           "Animal Care",
                           "Library & Publishing",
                           "Fashion")


industry_map <- hash()

for(i in standard_industry)
{
  industry_map[[as.character(i)]] <- c("")
}

for(i in non_standard_industry)
{
  industry_map[[as.character(i)]] <- c("")
}

 
ask_a_manager_2021_cleaned%>%
  filter(industry %in% standard_industry)
# roughly 6000 people used the other function within the industry section.....
```


```{r industry-cleaning}
# identify all instances put down to the other category
outliers_table <- ask_a_manager_2021_cleaned%>%
  select(industry)%>%
  filter(!industry %in% standard_industry)%>%
  mutate(industry = tolower(industry))

#make a list out of it
outliers <-  tolower(unique(ask_a_manager_2021_cleaned$industry[!ask_a_manager_2021_cleaned$industry %in% standard_industry]))

science_related <- outliers[grep("science",outliers)]
```
### Higher education

```{r industry-cleaning}
# Higher education
industry_map[["Education (Higher Education)"]] <- outliers[grep("academ",outliers)]


industry_map[["Education (Higher Education)"]] <- industry_map[["Education (Higher Education)"]][-grep("non-aca",industry_map[["Education (Higher Education)"]])]

industry_map[["Education (Higher Education)"]]<- industry_map[["Education (Higher Education)"]][-grep("not",industry_map[["Education (Higher Education)"]])]

industry_map[["Education (Higher Education)"]]<- c(outliers[grep("higher educ",outliers)],
                                                   industry_map[["Education (Higher Education)"]])

industry_map[["Education (Higher Education)"]]<- c(outliers[grep("university",outliers)],
                                                   industry_map[["Education (Higher Education)"]])

industry_map[["Education (Higher Education)"]]<- c(outliers[grep("college",outliers)],
                                                   industry_map[["Education (Higher Education)"]])
outliers_classified <- industry_map[["Education (Higher Education)"]]
```

### Sales
```{r industry-cleaning}
industry_map[["Sales"]] <- c(outliers[grep("procurement",outliers)],
                                       industry_map[["Sales"]])


outliers_classified <-c(industry_map[["Sales"]],
                        outliers_classified)
```

### Banking and Finance
```{r industry-cleaning}
industry_map[["Accounting, Banking & Finance"]] <-  c(outliers[grep("acturial",outliers)],
                                       industry_map[["Accounting, Banking & Finance"]])

industry_map[["Accounting, Banking & Finance"]] <-  c(outliers[grep("finance",outliers)],
                                       industry_map[["Accounting, Banking & Finance"]])

industry_map[["Accounting, Banking & Finance"]] <-  c(outliers[grep("private equity",outliers)],
                                       industry_map[["Accounting, Banking & Finance"]])


outliers_classified <-c(industry_map[["Accounting, Banking & Finance"]],
                        outliers_classified)
```

### Engineering Manufacturing
```{r industry-cleaning}

industry_map[["Engineering or Manufacturing"]] <-c()

industry_map[["Engineering or Manufacturing"]] <- c(outliers[grep("^(?=.*manufactur)(?!.*food)(?!.*aerospace)",outliers, perl = TRUE)],
                                       industry_map[["Engineering or Manufacturing"]])

industry_map[["Engineering or Manufacturing"]]

outliers_classified <-c(industry_map[["Engineering or Manufacturing"]],
                        outliers_classified)
```

### Health Care
```{r industry-cleaning}
industry_map[["Health care"]] <-c()

industry_map[["Health care"]] <- c(outliers[grep("^(?=.*medical)(?!.*not)",outliers, perl = TRUE)],
                                   industry_map[["Health care"]])

industry_map[["Health care"]] <- c(outliers[grep("pharmaceuticals",outliers)],
                                   industry_map[["Health care"]])

industry_map[["Health care"]] <- c(outliers[grep("beauty",outliers)],
                                   industry_map[["Health care"]])

outliers_classified <-c(industry_map[["Health care"]],
                        outliers_classified)

industry_map[["Health care"]]
```

### Tech
```{r industry-cleaning}
industry_map[["Computing or Tech"]] <- c(outliers[grep("^tech$",outliers)],
                                   industry_map[["Computing or Tech"]])

industry_map[["Computing or Tech"]] <- c(outliers[grep("^technology",outliers)],
                                   industry_map[["Computing or Tech"]])

industry_map[["Computing or Tech"]] <- c(outliers[grep("software",outliers)],
                                   industry_map[["Computing or Tech"]])

industry_map[["Computing or Tech"]] <- c(outliers[grep("internet",outliers)],
                                   industry_map[["Computing or Tech"]])

outliers_classified <-c(industry_map[["Computing or Tech"]],
                        outliers_classified)
```

### Transport or Logistics

```{r industry-cleaning}
industry_map[["Transport or Logistics"]] <- c(outliers[grep("distribution",outliers)],
                                   industry_map[["Transport or Logistics"]])

industry_map[["Transport or Logistics"]] <- c(outliers[grep("import",outliers)],
                                   industry_map[["Transport or Logistics"]])

industry_map[["Transport or Logistics"]] <- c(outliers[grep("supply chain",outliers)],
                                   industry_map[["Transport or Logistics"]])

outliers_classified <-c(industry_map[["Transport or Logistics"]],
                        outliers_classified)
```

### Government and Public Administration
```{r industry-cleaning}
industry_map[["Government and Public Administration"]] <- c(outliers[grep("government",outliers)],
                                   industry_map[["Government and Public Administration"]])

industry_map[["Government and Public Administration"]] <- c(outliers[grep("politics",outliers)],
                                   industry_map[["Government and Public Administration"]])

industry_map[["Government and Public Administration"]] <- c(outliers[grep("administration",outliers)],
                                   industry_map[["Government and Public Administration"]])

industry_map[["Government and Public Administration"]] <- c(outliers[grep("public health",outliers)],
                                   industry_map[["Government and Public Administration"]])

outliers_classified <-c(industry_map[["Government and Public Administration"]],
                        outliers_classified)
```

### Property or Construction
```{r industry-cleaning}
industry_map[["Property or Construction"]] <- c(outliers[grep("architect",outliers)],
                                   industry_map[["Property or Construction"]])

outliers_classified <-c(industry_map[["Property or Construction"]],
                        outliers_classified)
```

### Aerospace & Defence
```{r industry-cleaning}
industry_map[["Aerospace & Defence"]] <- c(outliers[grep("aerospace",outliers)],
                                   industry_map[["Aerospace & Defence"]])

outliers_classified <-c(industry_map[["Aerospace & Defence"]],
                        outliers_classified)
```

### Mining and Metal
```{r industry-cleaning}

industry_map[["Mining and Mentals"]] <- c(outliers[grep("mining",outliers)],
                                   industry_map[["Mining and Mentals"]])

outliers_classified <-c(industry_map[["Mining and Mentals"]],
                        outliers_classified)
```



```{r}
values(industry_map)

# check outliers reamining

outliers_left <- outliers_table%>%
  filter(!industry %in% outliers_classified)
outliers_left

```


**Adding ISCO classification to the dataset** 
```{r industry-cleaning}
occupation_classification <- labourR::classify_occupation(corpus = ask_a_manager_2021_cleaned, 
                                          isco_level = 2, 
                                          lang = "en",
                                          num_leaves = 10,
                                          text_col = "industry",
                                          id = "timestamp")%>%
   mutate(timestamp = ymd_hms(timestamp))

ask_a_manager_2021_cleaned <- ask_a_manager_2021_cleaned%>%
  mutate(timestamp = ymd_hms(timestamp))

ask_a_manager_2021_cleaned <- left_join(ask_a_manager_2021_cleaned,
           occupation_classification,
           by = "timestamp")%>%
   clean_names()

labR_classifications <- unique(occupation_classification$preferredLabel)
labR_classifications

```








